### ISSUE TITLE
Error: Cannot find module 'astronomia/julian' with version 3.3.0

### ISSUE THREAD

**Issue by viljark** [commenthol/date-holidays#242]
Getting this error after upgrading from 1.9.1 to 3.3.0.

Using it in TS project like this:

```
import Holidays from 'date-holidays'
const holidays = new Holidays('FI').isHoliday(date)
```

stack:
```
[API] Error: Cannot find module 'astronomia/julian'
[API] Require stack:
[API] - /project/node_modules/date-holidays-parser/lib/Julian.cjs
[API] - /project/node_modules/date-holidays-parser/lib/CalEventFactory.cjs

```

tsconfig.json

```
{
	"compilerOptions": {
		"target": "es2016",
		"module": "commonjs",
		"outDir": "./dist",
		"moduleResolution": "node",
		"lib": ["es2017", "es2018", "esnext", "dom"],
		"typeRoots": ["./@types", "./node_modules/@types", "../../node_modules/@types"],
		"strict": true,
		"noImplicitReturns": true,
		"noUnusedParameters": true,
		"noUnusedLocals": false,
		"sourceMap": true,
		"skipLibCheck": true,
		"pretty": true,
		"resolveJsonModule": true,
		"esModuleInterop": true,
		"allowSyntheticDefaultImports": true,
		"allowJs": true,
		"preserveWatchOutput": true
	}
}
```

**Comment by commenthol** [comment]
What node version are you using?
Would you mind setting up a sample project on github which shows this issue?

**Comment by commenthol** [comment]
I have tried with the above tsconfig.json on node@16.1.0 without any problems.
Please consider a fresh install of your project:
    
    rimraf node_modules package-lock.json yarn.lock
    npm i

**Comment by viljark** [comment]
I'm using node v12.16.2, yarn 1.22.4, npm 6.14.4

I tried to re-create my issue, but I can't reproduce it while running in CodeSandbox, but it fails when I download it and run it in my machine with `yarn start` or `npm run start`.

Here is the CodeSandbox https://codesandbox.io/s/github/viljark/date-holidays-bug-repro/tree/main/

And here is the Github repo https://github.com/viljark/date-holidays-bug-repro

**Comment by commenthol** [comment]
Hi @viljark, I cloned your repo, did npm install and all works. So from my point of view it's unrelated to date-holidays.  
```
$ npm version
{
  'date-holidays-bug-repro': '1.0.0',
  npm: '6.14.12',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  http_parser: '2.9.4',
  icu: '67.1',
  llhttp: '2.1.3',
  modules: '72',
  napi: '8',
  nghttp2: '1.41.0',
  node: '12.22.1',
  openssl: '1.1.1k',
  tz: '2019c',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '7.8.279.23-node.46',
  zlib: '1.2.11'
}
```

**Comment by viljark** [comment]
Thanks for looking into it. 
I upgaded from node 12.16.2 to 14.17.0 and everything works now. 🤷
